# Generated by Django 3.1.7 on 2021-03-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nboard', '0005_auto_20210329_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hits',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
